name: eczema_core_generated_hooks

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  mason: ">=0.1.0-dev.40 <0.1.0"
  json_to_dart:
    git: 
      url: https://github.com/robbysoerya/json_to_dart
      ref: main
